// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestBedLogMessage.proto

package com.brix.testbed.monitor.protobuf;

public final class TestBedLogMessageProto {
  private TestBedLogMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestBedLogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bean.TestBedLog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string hostName = 2;</code>
     */
    java.lang.String getHostName();
    /**
     * <code>string hostName = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostNameBytes();

    /**
     * <code>repeated .bean.LogMessage logMessage = 3;</code>
     */
    java.util.List<com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage> 
        getLogMessageList();
    /**
     * <code>repeated .bean.LogMessage logMessage = 3;</code>
     */
    com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage getLogMessage(int index);
    /**
     * <code>repeated .bean.LogMessage logMessage = 3;</code>
     */
    int getLogMessageCount();
    /**
     * <code>repeated .bean.LogMessage logMessage = 3;</code>
     */
    java.util.List<? extends com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessageOrBuilder> 
        getLogMessageOrBuilderList();
    /**
     * <code>repeated .bean.LogMessage logMessage = 3;</code>
     */
    com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessageOrBuilder getLogMessageOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code bean.TestBedLog}
   */
  public  static final class TestBedLog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bean.TestBedLog)
      TestBedLogOrBuilder {
    // Use TestBedLog.newBuilder() to construct.
    private TestBedLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestBedLog() {
      name_ = "";
      hostName_ = "";
      logMessage_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TestBedLog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              hostName_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                logMessage_ = new java.util.ArrayList<com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage>();
                mutable_bitField0_ |= 0x00000004;
              }
              logMessage_.add(
                  input.readMessage(com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          logMessage_ = java.util.Collections.unmodifiableList(logMessage_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.internal_static_bean_TestBedLog_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.internal_static_bean_TestBedLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog.class, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOSTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object hostName_;
    /**
     * <code>string hostName = 2;</code>
     */
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      }
    }
    /**
     * <code>string hostName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGMESSAGE_FIELD_NUMBER = 3;
    private java.util.List<com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage> logMessage_;
    /**
     * <code>repeated .bean.LogMessage logMessage = 3;</code>
     */
    public java.util.List<com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage> getLogMessageList() {
      return logMessage_;
    }
    /**
     * <code>repeated .bean.LogMessage logMessage = 3;</code>
     */
    public java.util.List<? extends com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessageOrBuilder> 
        getLogMessageOrBuilderList() {
      return logMessage_;
    }
    /**
     * <code>repeated .bean.LogMessage logMessage = 3;</code>
     */
    public int getLogMessageCount() {
      return logMessage_.size();
    }
    /**
     * <code>repeated .bean.LogMessage logMessage = 3;</code>
     */
    public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage getLogMessage(int index) {
      return logMessage_.get(index);
    }
    /**
     * <code>repeated .bean.LogMessage logMessage = 3;</code>
     */
    public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessageOrBuilder getLogMessageOrBuilder(
        int index) {
      return logMessage_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getHostNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hostName_);
      }
      for (int i = 0; i < logMessage_.size(); i++) {
        output.writeMessage(3, logMessage_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getHostNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hostName_);
      }
      for (int i = 0; i < logMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, logMessage_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog)) {
        return super.equals(obj);
      }
      com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog other = (com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getHostName()
          .equals(other.getHostName());
      result = result && getLogMessageList()
          .equals(other.getLogMessageList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getHostName().hashCode();
      if (getLogMessageCount() > 0) {
        hash = (37 * hash) + LOGMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getLogMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bean.TestBedLog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bean.TestBedLog)
        com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.internal_static_bean_TestBedLog_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.internal_static_bean_TestBedLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog.class, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog.Builder.class);
      }

      // Construct using com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLogMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        hostName_ = "";

        if (logMessageBuilder_ == null) {
          logMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          logMessageBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.internal_static_bean_TestBedLog_descriptor;
      }

      public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog getDefaultInstanceForType() {
        return com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog.getDefaultInstance();
      }

      public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog build() {
        com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog buildPartial() {
        com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog result = new com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.hostName_ = hostName_;
        if (logMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            logMessage_ = java.util.Collections.unmodifiableList(logMessage_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.logMessage_ = logMessage_;
        } else {
          result.logMessage_ = logMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog) {
          return mergeFrom((com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog other) {
        if (other == com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getHostName().isEmpty()) {
          hostName_ = other.hostName_;
          onChanged();
        }
        if (logMessageBuilder_ == null) {
          if (!other.logMessage_.isEmpty()) {
            if (logMessage_.isEmpty()) {
              logMessage_ = other.logMessage_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureLogMessageIsMutable();
              logMessage_.addAll(other.logMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.logMessage_.isEmpty()) {
            if (logMessageBuilder_.isEmpty()) {
              logMessageBuilder_.dispose();
              logMessageBuilder_ = null;
              logMessage_ = other.logMessage_;
              bitField0_ = (bitField0_ & ~0x00000004);
              logMessageBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLogMessageFieldBuilder() : null;
            } else {
              logMessageBuilder_.addAllMessages(other.logMessage_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hostName_ = "";
      /**
       * <code>string hostName = 2;</code>
       */
      public java.lang.String getHostName() {
        java.lang.Object ref = hostName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hostName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hostName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostNameBytes() {
        java.lang.Object ref = hostName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hostName = 2;</code>
       */
      public Builder setHostName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hostName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hostName = 2;</code>
       */
      public Builder clearHostName() {
        
        hostName_ = getDefaultInstance().getHostName();
        onChanged();
        return this;
      }
      /**
       * <code>string hostName = 2;</code>
       */
      public Builder setHostNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hostName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage> logMessage_ =
        java.util.Collections.emptyList();
      private void ensureLogMessageIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          logMessage_ = new java.util.ArrayList<com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage>(logMessage_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.Builder, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessageOrBuilder> logMessageBuilder_;

      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public java.util.List<com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage> getLogMessageList() {
        if (logMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(logMessage_);
        } else {
          return logMessageBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public int getLogMessageCount() {
        if (logMessageBuilder_ == null) {
          return logMessage_.size();
        } else {
          return logMessageBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage getLogMessage(int index) {
        if (logMessageBuilder_ == null) {
          return logMessage_.get(index);
        } else {
          return logMessageBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public Builder setLogMessage(
          int index, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage value) {
        if (logMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogMessageIsMutable();
          logMessage_.set(index, value);
          onChanged();
        } else {
          logMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public Builder setLogMessage(
          int index, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.Builder builderForValue) {
        if (logMessageBuilder_ == null) {
          ensureLogMessageIsMutable();
          logMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          logMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public Builder addLogMessage(com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage value) {
        if (logMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogMessageIsMutable();
          logMessage_.add(value);
          onChanged();
        } else {
          logMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public Builder addLogMessage(
          int index, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage value) {
        if (logMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogMessageIsMutable();
          logMessage_.add(index, value);
          onChanged();
        } else {
          logMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public Builder addLogMessage(
          com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.Builder builderForValue) {
        if (logMessageBuilder_ == null) {
          ensureLogMessageIsMutable();
          logMessage_.add(builderForValue.build());
          onChanged();
        } else {
          logMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public Builder addLogMessage(
          int index, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.Builder builderForValue) {
        if (logMessageBuilder_ == null) {
          ensureLogMessageIsMutable();
          logMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          logMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public Builder addAllLogMessage(
          java.lang.Iterable<? extends com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage> values) {
        if (logMessageBuilder_ == null) {
          ensureLogMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, logMessage_);
          onChanged();
        } else {
          logMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public Builder clearLogMessage() {
        if (logMessageBuilder_ == null) {
          logMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          logMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public Builder removeLogMessage(int index) {
        if (logMessageBuilder_ == null) {
          ensureLogMessageIsMutable();
          logMessage_.remove(index);
          onChanged();
        } else {
          logMessageBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.Builder getLogMessageBuilder(
          int index) {
        return getLogMessageFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessageOrBuilder getLogMessageOrBuilder(
          int index) {
        if (logMessageBuilder_ == null) {
          return logMessage_.get(index);  } else {
          return logMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public java.util.List<? extends com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessageOrBuilder> 
           getLogMessageOrBuilderList() {
        if (logMessageBuilder_ != null) {
          return logMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(logMessage_);
        }
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.Builder addLogMessageBuilder() {
        return getLogMessageFieldBuilder().addBuilder(
            com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.Builder addLogMessageBuilder(
          int index) {
        return getLogMessageFieldBuilder().addBuilder(
            index, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .bean.LogMessage logMessage = 3;</code>
       */
      public java.util.List<com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.Builder> 
           getLogMessageBuilderList() {
        return getLogMessageFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.Builder, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessageOrBuilder> 
          getLogMessageFieldBuilder() {
        if (logMessageBuilder_ == null) {
          logMessageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.Builder, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessageOrBuilder>(
                  logMessage_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          logMessage_ = null;
        }
        return logMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bean.TestBedLog)
    }

    // @@protoc_insertion_point(class_scope:bean.TestBedLog)
    private static final com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog();
    }

    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestBedLog>
        PARSER = new com.google.protobuf.AbstractParser<TestBedLog>() {
      public TestBedLog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TestBedLog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestBedLog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestBedLog> getParserForType() {
      return PARSER;
    }

    public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.TestBedLog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LogMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bean.LogMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 1;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>int32 severity = 2;</code>
     */
    int getSeverity();

    /**
     * <code>int32 type = 3;</code>
     */
    int getType();

    /**
     * <code>string dateTime = 4;</code>
     */
    java.lang.String getDateTime();
    /**
     * <code>string dateTime = 4;</code>
     */
    com.google.protobuf.ByteString
        getDateTimeBytes();

    /**
     * <code>int32 seqNo = 5;</code>
     */
    int getSeqNo();
  }
  /**
   * Protobuf type {@code bean.LogMessage}
   */
  public  static final class LogMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bean.LogMessage)
      LogMessageOrBuilder {
    // Use LogMessage.newBuilder() to construct.
    private LogMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogMessage() {
      value_ = "";
      severity_ = 0;
      type_ = 0;
      dateTime_ = "";
      seqNo_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LogMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            case 16: {

              severity_ = input.readInt32();
              break;
            }
            case 24: {

              type_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              dateTime_ = s;
              break;
            }
            case 40: {

              seqNo_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.internal_static_bean_LogMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.internal_static_bean_LogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.class, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 1;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEVERITY_FIELD_NUMBER = 2;
    private int severity_;
    /**
     * <code>int32 severity = 2;</code>
     */
    public int getSeverity() {
      return severity_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>int32 type = 3;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int DATETIME_FIELD_NUMBER = 4;
    private volatile java.lang.Object dateTime_;
    /**
     * <code>string dateTime = 4;</code>
     */
    public java.lang.String getDateTime() {
      java.lang.Object ref = dateTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateTime_ = s;
        return s;
      }
    }
    /**
     * <code>string dateTime = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDateTimeBytes() {
      java.lang.Object ref = dateTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQNO_FIELD_NUMBER = 5;
    private int seqNo_;
    /**
     * <code>int32 seqNo = 5;</code>
     */
    public int getSeqNo() {
      return seqNo_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
      if (severity_ != 0) {
        output.writeInt32(2, severity_);
      }
      if (type_ != 0) {
        output.writeInt32(3, type_);
      }
      if (!getDateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dateTime_);
      }
      if (seqNo_ != 0) {
        output.writeInt32(5, seqNo_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      if (severity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, severity_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (!getDateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dateTime_);
      }
      if (seqNo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, seqNo_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage)) {
        return super.equals(obj);
      }
      com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage other = (com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage) obj;

      boolean result = true;
      result = result && getValue()
          .equals(other.getValue());
      result = result && (getSeverity()
          == other.getSeverity());
      result = result && (getType()
          == other.getType());
      result = result && getDateTime()
          .equals(other.getDateTime());
      result = result && (getSeqNo()
          == other.getSeqNo());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + SEVERITY_FIELD_NUMBER;
      hash = (53 * hash) + getSeverity();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + DATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getDateTime().hashCode();
      hash = (37 * hash) + SEQNO_FIELD_NUMBER;
      hash = (53 * hash) + getSeqNo();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bean.LogMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bean.LogMessage)
        com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.internal_static_bean_LogMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.internal_static_bean_LogMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.class, com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.Builder.class);
      }

      // Construct using com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = "";

        severity_ = 0;

        type_ = 0;

        dateTime_ = "";

        seqNo_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.internal_static_bean_LogMessage_descriptor;
      }

      public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage getDefaultInstanceForType() {
        return com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.getDefaultInstance();
      }

      public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage build() {
        com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage buildPartial() {
        com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage result = new com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage(this);
        result.value_ = value_;
        result.severity_ = severity_;
        result.type_ = type_;
        result.dateTime_ = dateTime_;
        result.seqNo_ = seqNo_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage) {
          return mergeFrom((com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage other) {
        if (other == com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        if (other.getSeverity() != 0) {
          setSeverity(other.getSeverity());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getDateTime().isEmpty()) {
          dateTime_ = other.dateTime_;
          onChanged();
        }
        if (other.getSeqNo() != 0) {
          setSeqNo(other.getSeqNo());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 1;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }

      private int severity_ ;
      /**
       * <code>int32 severity = 2;</code>
       */
      public int getSeverity() {
        return severity_;
      }
      /**
       * <code>int32 severity = 2;</code>
       */
      public Builder setSeverity(int value) {
        
        severity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 severity = 2;</code>
       */
      public Builder clearSeverity() {
        
        severity_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 3;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 3;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object dateTime_ = "";
      /**
       * <code>string dateTime = 4;</code>
       */
      public java.lang.String getDateTime() {
        java.lang.Object ref = dateTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dateTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dateTime = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDateTimeBytes() {
        java.lang.Object ref = dateTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dateTime = 4;</code>
       */
      public Builder setDateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dateTime = 4;</code>
       */
      public Builder clearDateTime() {
        
        dateTime_ = getDefaultInstance().getDateTime();
        onChanged();
        return this;
      }
      /**
       * <code>string dateTime = 4;</code>
       */
      public Builder setDateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dateTime_ = value;
        onChanged();
        return this;
      }

      private int seqNo_ ;
      /**
       * <code>int32 seqNo = 5;</code>
       */
      public int getSeqNo() {
        return seqNo_;
      }
      /**
       * <code>int32 seqNo = 5;</code>
       */
      public Builder setSeqNo(int value) {
        
        seqNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 seqNo = 5;</code>
       */
      public Builder clearSeqNo() {
        
        seqNo_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bean.LogMessage)
    }

    // @@protoc_insertion_point(class_scope:bean.LogMessage)
    private static final com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage();
    }

    public static com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogMessage>
        PARSER = new com.google.protobuf.AbstractParser<LogMessage>() {
      public LogMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LogMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogMessage> getParserForType() {
      return PARSER;
    }

    public com.brix.testbed.monitor.protobuf.TestBedLogMessageProto.LogMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bean_TestBedLog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bean_TestBedLog_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bean_LogMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bean_LogMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027TestBedLogMessage.proto\022\004bean\"R\n\nTestB" +
      "edLog\022\014\n\004name\030\001 \001(\t\022\020\n\010hostName\030\002 \001(\t\022$\n" +
      "\nlogMessage\030\003 \003(\0132\020.bean.LogMessage\"\\\n\nL" +
      "ogMessage\022\r\n\005value\030\001 \001(\t\022\020\n\010severity\030\002 \001" +
      "(\005\022\014\n\004type\030\003 \001(\005\022\020\n\010dateTime\030\004 \001(\t\022\r\n\005se" +
      "qNo\030\005 \001(\005B;\n!com.brix.testbed.monitor.pr" +
      "otobufB\026TestBedLogMessageProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bean_TestBedLog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bean_TestBedLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bean_TestBedLog_descriptor,
        new java.lang.String[] { "Name", "HostName", "LogMessage", });
    internal_static_bean_LogMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bean_LogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bean_LogMessage_descriptor,
        new java.lang.String[] { "Value", "Severity", "Type", "DateTime", "SeqNo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
