// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestBedAlarmProto.proto

package com.brix.testbed.monitor.protobuf;

public final class TestBedAlarmProto {
  private TestBedAlarmProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestBedAlarmOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bean.TestBedAlarm)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string hostName = 2;</code>
     */
    java.lang.String getHostName();
    /**
     * <code>string hostName = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostNameBytes();

    /**
     * <code>repeated .bean.Alarm alarms = 3;</code>
     */
    java.util.List<com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm> 
        getAlarmsList();
    /**
     * <code>repeated .bean.Alarm alarms = 3;</code>
     */
    com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm getAlarms(int index);
    /**
     * <code>repeated .bean.Alarm alarms = 3;</code>
     */
    int getAlarmsCount();
    /**
     * <code>repeated .bean.Alarm alarms = 3;</code>
     */
    java.util.List<? extends com.brix.testbed.monitor.protobuf.TestBedAlarmProto.AlarmOrBuilder> 
        getAlarmsOrBuilderList();
    /**
     * <code>repeated .bean.Alarm alarms = 3;</code>
     */
    com.brix.testbed.monitor.protobuf.TestBedAlarmProto.AlarmOrBuilder getAlarmsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code bean.TestBedAlarm}
   */
  public  static final class TestBedAlarm extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bean.TestBedAlarm)
      TestBedAlarmOrBuilder {
    // Use TestBedAlarm.newBuilder() to construct.
    private TestBedAlarm(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestBedAlarm() {
      name_ = "";
      hostName_ = "";
      alarms_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TestBedAlarm(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              hostName_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                alarms_ = new java.util.ArrayList<com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm>();
                mutable_bitField0_ |= 0x00000004;
              }
              alarms_.add(
                  input.readMessage(com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          alarms_ = java.util.Collections.unmodifiableList(alarms_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.brix.testbed.monitor.protobuf.TestBedAlarmProto.internal_static_bean_TestBedAlarm_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.brix.testbed.monitor.protobuf.TestBedAlarmProto.internal_static_bean_TestBedAlarm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm.class, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOSTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object hostName_;
    /**
     * <code>string hostName = 2;</code>
     */
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      }
    }
    /**
     * <code>string hostName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALARMS_FIELD_NUMBER = 3;
    private java.util.List<com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm> alarms_;
    /**
     * <code>repeated .bean.Alarm alarms = 3;</code>
     */
    public java.util.List<com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm> getAlarmsList() {
      return alarms_;
    }
    /**
     * <code>repeated .bean.Alarm alarms = 3;</code>
     */
    public java.util.List<? extends com.brix.testbed.monitor.protobuf.TestBedAlarmProto.AlarmOrBuilder> 
        getAlarmsOrBuilderList() {
      return alarms_;
    }
    /**
     * <code>repeated .bean.Alarm alarms = 3;</code>
     */
    public int getAlarmsCount() {
      return alarms_.size();
    }
    /**
     * <code>repeated .bean.Alarm alarms = 3;</code>
     */
    public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm getAlarms(int index) {
      return alarms_.get(index);
    }
    /**
     * <code>repeated .bean.Alarm alarms = 3;</code>
     */
    public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.AlarmOrBuilder getAlarmsOrBuilder(
        int index) {
      return alarms_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getHostNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hostName_);
      }
      for (int i = 0; i < alarms_.size(); i++) {
        output.writeMessage(3, alarms_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getHostNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hostName_);
      }
      for (int i = 0; i < alarms_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, alarms_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm)) {
        return super.equals(obj);
      }
      com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm other = (com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getHostName()
          .equals(other.getHostName());
      result = result && getAlarmsList()
          .equals(other.getAlarmsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getHostName().hashCode();
      if (getAlarmsCount() > 0) {
        hash = (37 * hash) + ALARMS_FIELD_NUMBER;
        hash = (53 * hash) + getAlarmsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bean.TestBedAlarm}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bean.TestBedAlarm)
        com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarmOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.brix.testbed.monitor.protobuf.TestBedAlarmProto.internal_static_bean_TestBedAlarm_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.brix.testbed.monitor.protobuf.TestBedAlarmProto.internal_static_bean_TestBedAlarm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm.class, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm.Builder.class);
      }

      // Construct using com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAlarmsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        hostName_ = "";

        if (alarmsBuilder_ == null) {
          alarms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          alarmsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.brix.testbed.monitor.protobuf.TestBedAlarmProto.internal_static_bean_TestBedAlarm_descriptor;
      }

      public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm getDefaultInstanceForType() {
        return com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm.getDefaultInstance();
      }

      public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm build() {
        com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm buildPartial() {
        com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm result = new com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.hostName_ = hostName_;
        if (alarmsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            alarms_ = java.util.Collections.unmodifiableList(alarms_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.alarms_ = alarms_;
        } else {
          result.alarms_ = alarmsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm) {
          return mergeFrom((com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm other) {
        if (other == com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getHostName().isEmpty()) {
          hostName_ = other.hostName_;
          onChanged();
        }
        if (alarmsBuilder_ == null) {
          if (!other.alarms_.isEmpty()) {
            if (alarms_.isEmpty()) {
              alarms_ = other.alarms_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAlarmsIsMutable();
              alarms_.addAll(other.alarms_);
            }
            onChanged();
          }
        } else {
          if (!other.alarms_.isEmpty()) {
            if (alarmsBuilder_.isEmpty()) {
              alarmsBuilder_.dispose();
              alarmsBuilder_ = null;
              alarms_ = other.alarms_;
              bitField0_ = (bitField0_ & ~0x00000004);
              alarmsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAlarmsFieldBuilder() : null;
            } else {
              alarmsBuilder_.addAllMessages(other.alarms_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hostName_ = "";
      /**
       * <code>string hostName = 2;</code>
       */
      public java.lang.String getHostName() {
        java.lang.Object ref = hostName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hostName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hostName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostNameBytes() {
        java.lang.Object ref = hostName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hostName = 2;</code>
       */
      public Builder setHostName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hostName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hostName = 2;</code>
       */
      public Builder clearHostName() {
        
        hostName_ = getDefaultInstance().getHostName();
        onChanged();
        return this;
      }
      /**
       * <code>string hostName = 2;</code>
       */
      public Builder setHostNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hostName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm> alarms_ =
        java.util.Collections.emptyList();
      private void ensureAlarmsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          alarms_ = new java.util.ArrayList<com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm>(alarms_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.Builder, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.AlarmOrBuilder> alarmsBuilder_;

      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public java.util.List<com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm> getAlarmsList() {
        if (alarmsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(alarms_);
        } else {
          return alarmsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public int getAlarmsCount() {
        if (alarmsBuilder_ == null) {
          return alarms_.size();
        } else {
          return alarmsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm getAlarms(int index) {
        if (alarmsBuilder_ == null) {
          return alarms_.get(index);
        } else {
          return alarmsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public Builder setAlarms(
          int index, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm value) {
        if (alarmsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlarmsIsMutable();
          alarms_.set(index, value);
          onChanged();
        } else {
          alarmsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public Builder setAlarms(
          int index, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.Builder builderForValue) {
        if (alarmsBuilder_ == null) {
          ensureAlarmsIsMutable();
          alarms_.set(index, builderForValue.build());
          onChanged();
        } else {
          alarmsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public Builder addAlarms(com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm value) {
        if (alarmsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlarmsIsMutable();
          alarms_.add(value);
          onChanged();
        } else {
          alarmsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public Builder addAlarms(
          int index, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm value) {
        if (alarmsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlarmsIsMutable();
          alarms_.add(index, value);
          onChanged();
        } else {
          alarmsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public Builder addAlarms(
          com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.Builder builderForValue) {
        if (alarmsBuilder_ == null) {
          ensureAlarmsIsMutable();
          alarms_.add(builderForValue.build());
          onChanged();
        } else {
          alarmsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public Builder addAlarms(
          int index, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.Builder builderForValue) {
        if (alarmsBuilder_ == null) {
          ensureAlarmsIsMutable();
          alarms_.add(index, builderForValue.build());
          onChanged();
        } else {
          alarmsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public Builder addAllAlarms(
          java.lang.Iterable<? extends com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm> values) {
        if (alarmsBuilder_ == null) {
          ensureAlarmsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, alarms_);
          onChanged();
        } else {
          alarmsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public Builder clearAlarms() {
        if (alarmsBuilder_ == null) {
          alarms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          alarmsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public Builder removeAlarms(int index) {
        if (alarmsBuilder_ == null) {
          ensureAlarmsIsMutable();
          alarms_.remove(index);
          onChanged();
        } else {
          alarmsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.Builder getAlarmsBuilder(
          int index) {
        return getAlarmsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.AlarmOrBuilder getAlarmsOrBuilder(
          int index) {
        if (alarmsBuilder_ == null) {
          return alarms_.get(index);  } else {
          return alarmsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public java.util.List<? extends com.brix.testbed.monitor.protobuf.TestBedAlarmProto.AlarmOrBuilder> 
           getAlarmsOrBuilderList() {
        if (alarmsBuilder_ != null) {
          return alarmsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(alarms_);
        }
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.Builder addAlarmsBuilder() {
        return getAlarmsFieldBuilder().addBuilder(
            com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.getDefaultInstance());
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.Builder addAlarmsBuilder(
          int index) {
        return getAlarmsFieldBuilder().addBuilder(
            index, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.getDefaultInstance());
      }
      /**
       * <code>repeated .bean.Alarm alarms = 3;</code>
       */
      public java.util.List<com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.Builder> 
           getAlarmsBuilderList() {
        return getAlarmsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.Builder, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.AlarmOrBuilder> 
          getAlarmsFieldBuilder() {
        if (alarmsBuilder_ == null) {
          alarmsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.Builder, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.AlarmOrBuilder>(
                  alarms_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          alarms_ = null;
        }
        return alarmsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bean.TestBedAlarm)
    }

    // @@protoc_insertion_point(class_scope:bean.TestBedAlarm)
    private static final com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm();
    }

    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestBedAlarm>
        PARSER = new com.google.protobuf.AbstractParser<TestBedAlarm>() {
      public TestBedAlarm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TestBedAlarm(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestBedAlarm> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestBedAlarm> getParserForType() {
      return PARSER;
    }

    public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.TestBedAlarm getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AlarmOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bean.Alarm)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>double doubleValue = 2;</code>
     */
    double getDoubleValue();

    /**
     * <code>string strValue = 3;</code>
     */
    java.lang.String getStrValue();
    /**
     * <code>string strValue = 3;</code>
     */
    com.google.protobuf.ByteString
        getStrValueBytes();

    /**
     * <code>int32 dataType = 4;</code>
     */
    int getDataType();

    /**
     * <code>string unit = 5;</code>
     */
    java.lang.String getUnit();
    /**
     * <code>string unit = 5;</code>
     */
    com.google.protobuf.ByteString
        getUnitBytes();

    /**
     * <code>int32 alarmValue = 6;</code>
     */
    int getAlarmValue();

    /**
     * <code>int32 alarmAckflag = 7;</code>
     */
    int getAlarmAckflag();

    /**
     * <code>int32 seqNo = 8;</code>
     */
    int getSeqNo();

    /**
     * <code>string displayFormat = 9;</code>
     */
    java.lang.String getDisplayFormat();
    /**
     * <code>string displayFormat = 9;</code>
     */
    com.google.protobuf.ByteString
        getDisplayFormatBytes();

    /**
     * <code>string lowerAlarm = 10;</code>
     */
    java.lang.String getLowerAlarm();
    /**
     * <code>string lowerAlarm = 10;</code>
     */
    com.google.protobuf.ByteString
        getLowerAlarmBytes();

    /**
     * <code>string lowerWarning = 11;</code>
     */
    java.lang.String getLowerWarning();
    /**
     * <code>string lowerWarning = 11;</code>
     */
    com.google.protobuf.ByteString
        getLowerWarningBytes();

    /**
     * <code>string upperAlarm = 12;</code>
     */
    java.lang.String getUpperAlarm();
    /**
     * <code>string upperAlarm = 12;</code>
     */
    com.google.protobuf.ByteString
        getUpperAlarmBytes();

    /**
     * <code>string upperWarning = 13;</code>
     */
    java.lang.String getUpperWarning();
    /**
     * <code>string upperWarning = 13;</code>
     */
    com.google.protobuf.ByteString
        getUpperWarningBytes();
  }
  /**
   * Protobuf type {@code bean.Alarm}
   */
  public  static final class Alarm extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bean.Alarm)
      AlarmOrBuilder {
    // Use Alarm.newBuilder() to construct.
    private Alarm(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Alarm() {
      name_ = "";
      doubleValue_ = 0D;
      strValue_ = "";
      dataType_ = 0;
      unit_ = "";
      alarmValue_ = 0;
      alarmAckflag_ = 0;
      seqNo_ = 0;
      displayFormat_ = "";
      lowerAlarm_ = "";
      lowerWarning_ = "";
      upperAlarm_ = "";
      upperWarning_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Alarm(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 17: {

              doubleValue_ = input.readDouble();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              strValue_ = s;
              break;
            }
            case 32: {

              dataType_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              unit_ = s;
              break;
            }
            case 48: {

              alarmValue_ = input.readInt32();
              break;
            }
            case 56: {

              alarmAckflag_ = input.readInt32();
              break;
            }
            case 64: {

              seqNo_ = input.readInt32();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              displayFormat_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              lowerAlarm_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              lowerWarning_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              upperAlarm_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              upperWarning_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.brix.testbed.monitor.protobuf.TestBedAlarmProto.internal_static_bean_Alarm_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.brix.testbed.monitor.protobuf.TestBedAlarmProto.internal_static_bean_Alarm_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.class, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOUBLEVALUE_FIELD_NUMBER = 2;
    private double doubleValue_;
    /**
     * <code>double doubleValue = 2;</code>
     */
    public double getDoubleValue() {
      return doubleValue_;
    }

    public static final int STRVALUE_FIELD_NUMBER = 3;
    private volatile java.lang.Object strValue_;
    /**
     * <code>string strValue = 3;</code>
     */
    public java.lang.String getStrValue() {
      java.lang.Object ref = strValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        strValue_ = s;
        return s;
      }
    }
    /**
     * <code>string strValue = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStrValueBytes() {
      java.lang.Object ref = strValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATATYPE_FIELD_NUMBER = 4;
    private int dataType_;
    /**
     * <code>int32 dataType = 4;</code>
     */
    public int getDataType() {
      return dataType_;
    }

    public static final int UNIT_FIELD_NUMBER = 5;
    private volatile java.lang.Object unit_;
    /**
     * <code>string unit = 5;</code>
     */
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unit_ = s;
        return s;
      }
    }
    /**
     * <code>string unit = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALARMVALUE_FIELD_NUMBER = 6;
    private int alarmValue_;
    /**
     * <code>int32 alarmValue = 6;</code>
     */
    public int getAlarmValue() {
      return alarmValue_;
    }

    public static final int ALARMACKFLAG_FIELD_NUMBER = 7;
    private int alarmAckflag_;
    /**
     * <code>int32 alarmAckflag = 7;</code>
     */
    public int getAlarmAckflag() {
      return alarmAckflag_;
    }

    public static final int SEQNO_FIELD_NUMBER = 8;
    private int seqNo_;
    /**
     * <code>int32 seqNo = 8;</code>
     */
    public int getSeqNo() {
      return seqNo_;
    }

    public static final int DISPLAYFORMAT_FIELD_NUMBER = 9;
    private volatile java.lang.Object displayFormat_;
    /**
     * <code>string displayFormat = 9;</code>
     */
    public java.lang.String getDisplayFormat() {
      java.lang.Object ref = displayFormat_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayFormat_ = s;
        return s;
      }
    }
    /**
     * <code>string displayFormat = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayFormatBytes() {
      java.lang.Object ref = displayFormat_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayFormat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOWERALARM_FIELD_NUMBER = 10;
    private volatile java.lang.Object lowerAlarm_;
    /**
     * <code>string lowerAlarm = 10;</code>
     */
    public java.lang.String getLowerAlarm() {
      java.lang.Object ref = lowerAlarm_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lowerAlarm_ = s;
        return s;
      }
    }
    /**
     * <code>string lowerAlarm = 10;</code>
     */
    public com.google.protobuf.ByteString
        getLowerAlarmBytes() {
      java.lang.Object ref = lowerAlarm_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lowerAlarm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOWERWARNING_FIELD_NUMBER = 11;
    private volatile java.lang.Object lowerWarning_;
    /**
     * <code>string lowerWarning = 11;</code>
     */
    public java.lang.String getLowerWarning() {
      java.lang.Object ref = lowerWarning_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lowerWarning_ = s;
        return s;
      }
    }
    /**
     * <code>string lowerWarning = 11;</code>
     */
    public com.google.protobuf.ByteString
        getLowerWarningBytes() {
      java.lang.Object ref = lowerWarning_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lowerWarning_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPPERALARM_FIELD_NUMBER = 12;
    private volatile java.lang.Object upperAlarm_;
    /**
     * <code>string upperAlarm = 12;</code>
     */
    public java.lang.String getUpperAlarm() {
      java.lang.Object ref = upperAlarm_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        upperAlarm_ = s;
        return s;
      }
    }
    /**
     * <code>string upperAlarm = 12;</code>
     */
    public com.google.protobuf.ByteString
        getUpperAlarmBytes() {
      java.lang.Object ref = upperAlarm_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        upperAlarm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPPERWARNING_FIELD_NUMBER = 13;
    private volatile java.lang.Object upperWarning_;
    /**
     * <code>string upperWarning = 13;</code>
     */
    public java.lang.String getUpperWarning() {
      java.lang.Object ref = upperWarning_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        upperWarning_ = s;
        return s;
      }
    }
    /**
     * <code>string upperWarning = 13;</code>
     */
    public com.google.protobuf.ByteString
        getUpperWarningBytes() {
      java.lang.Object ref = upperWarning_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        upperWarning_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (doubleValue_ != 0D) {
        output.writeDouble(2, doubleValue_);
      }
      if (!getStrValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, strValue_);
      }
      if (dataType_ != 0) {
        output.writeInt32(4, dataType_);
      }
      if (!getUnitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, unit_);
      }
      if (alarmValue_ != 0) {
        output.writeInt32(6, alarmValue_);
      }
      if (alarmAckflag_ != 0) {
        output.writeInt32(7, alarmAckflag_);
      }
      if (seqNo_ != 0) {
        output.writeInt32(8, seqNo_);
      }
      if (!getDisplayFormatBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, displayFormat_);
      }
      if (!getLowerAlarmBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, lowerAlarm_);
      }
      if (!getLowerWarningBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, lowerWarning_);
      }
      if (!getUpperAlarmBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, upperAlarm_);
      }
      if (!getUpperWarningBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, upperWarning_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (doubleValue_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, doubleValue_);
      }
      if (!getStrValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, strValue_);
      }
      if (dataType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, dataType_);
      }
      if (!getUnitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, unit_);
      }
      if (alarmValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, alarmValue_);
      }
      if (alarmAckflag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, alarmAckflag_);
      }
      if (seqNo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, seqNo_);
      }
      if (!getDisplayFormatBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, displayFormat_);
      }
      if (!getLowerAlarmBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, lowerAlarm_);
      }
      if (!getLowerWarningBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, lowerWarning_);
      }
      if (!getUpperAlarmBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, upperAlarm_);
      }
      if (!getUpperWarningBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, upperWarning_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm)) {
        return super.equals(obj);
      }
      com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm other = (com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (
          java.lang.Double.doubleToLongBits(getDoubleValue())
          == java.lang.Double.doubleToLongBits(
              other.getDoubleValue()));
      result = result && getStrValue()
          .equals(other.getStrValue());
      result = result && (getDataType()
          == other.getDataType());
      result = result && getUnit()
          .equals(other.getUnit());
      result = result && (getAlarmValue()
          == other.getAlarmValue());
      result = result && (getAlarmAckflag()
          == other.getAlarmAckflag());
      result = result && (getSeqNo()
          == other.getSeqNo());
      result = result && getDisplayFormat()
          .equals(other.getDisplayFormat());
      result = result && getLowerAlarm()
          .equals(other.getLowerAlarm());
      result = result && getLowerWarning()
          .equals(other.getLowerWarning());
      result = result && getUpperAlarm()
          .equals(other.getUpperAlarm());
      result = result && getUpperWarning()
          .equals(other.getUpperWarning());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DOUBLEVALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDoubleValue()));
      hash = (37 * hash) + STRVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getStrValue().hashCode();
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDataType();
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + getUnit().hashCode();
      hash = (37 * hash) + ALARMVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getAlarmValue();
      hash = (37 * hash) + ALARMACKFLAG_FIELD_NUMBER;
      hash = (53 * hash) + getAlarmAckflag();
      hash = (37 * hash) + SEQNO_FIELD_NUMBER;
      hash = (53 * hash) + getSeqNo();
      hash = (37 * hash) + DISPLAYFORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getDisplayFormat().hashCode();
      hash = (37 * hash) + LOWERALARM_FIELD_NUMBER;
      hash = (53 * hash) + getLowerAlarm().hashCode();
      hash = (37 * hash) + LOWERWARNING_FIELD_NUMBER;
      hash = (53 * hash) + getLowerWarning().hashCode();
      hash = (37 * hash) + UPPERALARM_FIELD_NUMBER;
      hash = (53 * hash) + getUpperAlarm().hashCode();
      hash = (37 * hash) + UPPERWARNING_FIELD_NUMBER;
      hash = (53 * hash) + getUpperWarning().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bean.Alarm}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bean.Alarm)
        com.brix.testbed.monitor.protobuf.TestBedAlarmProto.AlarmOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.brix.testbed.monitor.protobuf.TestBedAlarmProto.internal_static_bean_Alarm_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.brix.testbed.monitor.protobuf.TestBedAlarmProto.internal_static_bean_Alarm_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.class, com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.Builder.class);
      }

      // Construct using com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        doubleValue_ = 0D;

        strValue_ = "";

        dataType_ = 0;

        unit_ = "";

        alarmValue_ = 0;

        alarmAckflag_ = 0;

        seqNo_ = 0;

        displayFormat_ = "";

        lowerAlarm_ = "";

        lowerWarning_ = "";

        upperAlarm_ = "";

        upperWarning_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.brix.testbed.monitor.protobuf.TestBedAlarmProto.internal_static_bean_Alarm_descriptor;
      }

      public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm getDefaultInstanceForType() {
        return com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.getDefaultInstance();
      }

      public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm build() {
        com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm buildPartial() {
        com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm result = new com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm(this);
        result.name_ = name_;
        result.doubleValue_ = doubleValue_;
        result.strValue_ = strValue_;
        result.dataType_ = dataType_;
        result.unit_ = unit_;
        result.alarmValue_ = alarmValue_;
        result.alarmAckflag_ = alarmAckflag_;
        result.seqNo_ = seqNo_;
        result.displayFormat_ = displayFormat_;
        result.lowerAlarm_ = lowerAlarm_;
        result.lowerWarning_ = lowerWarning_;
        result.upperAlarm_ = upperAlarm_;
        result.upperWarning_ = upperWarning_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm) {
          return mergeFrom((com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm other) {
        if (other == com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getDoubleValue() != 0D) {
          setDoubleValue(other.getDoubleValue());
        }
        if (!other.getStrValue().isEmpty()) {
          strValue_ = other.strValue_;
          onChanged();
        }
        if (other.getDataType() != 0) {
          setDataType(other.getDataType());
        }
        if (!other.getUnit().isEmpty()) {
          unit_ = other.unit_;
          onChanged();
        }
        if (other.getAlarmValue() != 0) {
          setAlarmValue(other.getAlarmValue());
        }
        if (other.getAlarmAckflag() != 0) {
          setAlarmAckflag(other.getAlarmAckflag());
        }
        if (other.getSeqNo() != 0) {
          setSeqNo(other.getSeqNo());
        }
        if (!other.getDisplayFormat().isEmpty()) {
          displayFormat_ = other.displayFormat_;
          onChanged();
        }
        if (!other.getLowerAlarm().isEmpty()) {
          lowerAlarm_ = other.lowerAlarm_;
          onChanged();
        }
        if (!other.getLowerWarning().isEmpty()) {
          lowerWarning_ = other.lowerWarning_;
          onChanged();
        }
        if (!other.getUpperAlarm().isEmpty()) {
          upperAlarm_ = other.upperAlarm_;
          onChanged();
        }
        if (!other.getUpperWarning().isEmpty()) {
          upperWarning_ = other.upperWarning_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private double doubleValue_ ;
      /**
       * <code>double doubleValue = 2;</code>
       */
      public double getDoubleValue() {
        return doubleValue_;
      }
      /**
       * <code>double doubleValue = 2;</code>
       */
      public Builder setDoubleValue(double value) {
        
        doubleValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double doubleValue = 2;</code>
       */
      public Builder clearDoubleValue() {
        
        doubleValue_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object strValue_ = "";
      /**
       * <code>string strValue = 3;</code>
       */
      public java.lang.String getStrValue() {
        java.lang.Object ref = strValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          strValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string strValue = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStrValueBytes() {
        java.lang.Object ref = strValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string strValue = 3;</code>
       */
      public Builder setStrValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        strValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string strValue = 3;</code>
       */
      public Builder clearStrValue() {
        
        strValue_ = getDefaultInstance().getStrValue();
        onChanged();
        return this;
      }
      /**
       * <code>string strValue = 3;</code>
       */
      public Builder setStrValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        strValue_ = value;
        onChanged();
        return this;
      }

      private int dataType_ ;
      /**
       * <code>int32 dataType = 4;</code>
       */
      public int getDataType() {
        return dataType_;
      }
      /**
       * <code>int32 dataType = 4;</code>
       */
      public Builder setDataType(int value) {
        
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dataType = 4;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object unit_ = "";
      /**
       * <code>string unit = 5;</code>
       */
      public java.lang.String getUnit() {
        java.lang.Object ref = unit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unit = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unit = 5;</code>
       */
      public Builder setUnit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 5;</code>
       */
      public Builder clearUnit() {
        
        unit_ = getDefaultInstance().getUnit();
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 5;</code>
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        unit_ = value;
        onChanged();
        return this;
      }

      private int alarmValue_ ;
      /**
       * <code>int32 alarmValue = 6;</code>
       */
      public int getAlarmValue() {
        return alarmValue_;
      }
      /**
       * <code>int32 alarmValue = 6;</code>
       */
      public Builder setAlarmValue(int value) {
        
        alarmValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 alarmValue = 6;</code>
       */
      public Builder clearAlarmValue() {
        
        alarmValue_ = 0;
        onChanged();
        return this;
      }

      private int alarmAckflag_ ;
      /**
       * <code>int32 alarmAckflag = 7;</code>
       */
      public int getAlarmAckflag() {
        return alarmAckflag_;
      }
      /**
       * <code>int32 alarmAckflag = 7;</code>
       */
      public Builder setAlarmAckflag(int value) {
        
        alarmAckflag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 alarmAckflag = 7;</code>
       */
      public Builder clearAlarmAckflag() {
        
        alarmAckflag_ = 0;
        onChanged();
        return this;
      }

      private int seqNo_ ;
      /**
       * <code>int32 seqNo = 8;</code>
       */
      public int getSeqNo() {
        return seqNo_;
      }
      /**
       * <code>int32 seqNo = 8;</code>
       */
      public Builder setSeqNo(int value) {
        
        seqNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 seqNo = 8;</code>
       */
      public Builder clearSeqNo() {
        
        seqNo_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object displayFormat_ = "";
      /**
       * <code>string displayFormat = 9;</code>
       */
      public java.lang.String getDisplayFormat() {
        java.lang.Object ref = displayFormat_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          displayFormat_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string displayFormat = 9;</code>
       */
      public com.google.protobuf.ByteString
          getDisplayFormatBytes() {
        java.lang.Object ref = displayFormat_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          displayFormat_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string displayFormat = 9;</code>
       */
      public Builder setDisplayFormat(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        displayFormat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string displayFormat = 9;</code>
       */
      public Builder clearDisplayFormat() {
        
        displayFormat_ = getDefaultInstance().getDisplayFormat();
        onChanged();
        return this;
      }
      /**
       * <code>string displayFormat = 9;</code>
       */
      public Builder setDisplayFormatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        displayFormat_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lowerAlarm_ = "";
      /**
       * <code>string lowerAlarm = 10;</code>
       */
      public java.lang.String getLowerAlarm() {
        java.lang.Object ref = lowerAlarm_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lowerAlarm_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lowerAlarm = 10;</code>
       */
      public com.google.protobuf.ByteString
          getLowerAlarmBytes() {
        java.lang.Object ref = lowerAlarm_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lowerAlarm_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lowerAlarm = 10;</code>
       */
      public Builder setLowerAlarm(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lowerAlarm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lowerAlarm = 10;</code>
       */
      public Builder clearLowerAlarm() {
        
        lowerAlarm_ = getDefaultInstance().getLowerAlarm();
        onChanged();
        return this;
      }
      /**
       * <code>string lowerAlarm = 10;</code>
       */
      public Builder setLowerAlarmBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lowerAlarm_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lowerWarning_ = "";
      /**
       * <code>string lowerWarning = 11;</code>
       */
      public java.lang.String getLowerWarning() {
        java.lang.Object ref = lowerWarning_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lowerWarning_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lowerWarning = 11;</code>
       */
      public com.google.protobuf.ByteString
          getLowerWarningBytes() {
        java.lang.Object ref = lowerWarning_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lowerWarning_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lowerWarning = 11;</code>
       */
      public Builder setLowerWarning(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lowerWarning_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lowerWarning = 11;</code>
       */
      public Builder clearLowerWarning() {
        
        lowerWarning_ = getDefaultInstance().getLowerWarning();
        onChanged();
        return this;
      }
      /**
       * <code>string lowerWarning = 11;</code>
       */
      public Builder setLowerWarningBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lowerWarning_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object upperAlarm_ = "";
      /**
       * <code>string upperAlarm = 12;</code>
       */
      public java.lang.String getUpperAlarm() {
        java.lang.Object ref = upperAlarm_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          upperAlarm_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string upperAlarm = 12;</code>
       */
      public com.google.protobuf.ByteString
          getUpperAlarmBytes() {
        java.lang.Object ref = upperAlarm_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          upperAlarm_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string upperAlarm = 12;</code>
       */
      public Builder setUpperAlarm(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        upperAlarm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string upperAlarm = 12;</code>
       */
      public Builder clearUpperAlarm() {
        
        upperAlarm_ = getDefaultInstance().getUpperAlarm();
        onChanged();
        return this;
      }
      /**
       * <code>string upperAlarm = 12;</code>
       */
      public Builder setUpperAlarmBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        upperAlarm_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object upperWarning_ = "";
      /**
       * <code>string upperWarning = 13;</code>
       */
      public java.lang.String getUpperWarning() {
        java.lang.Object ref = upperWarning_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          upperWarning_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string upperWarning = 13;</code>
       */
      public com.google.protobuf.ByteString
          getUpperWarningBytes() {
        java.lang.Object ref = upperWarning_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          upperWarning_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string upperWarning = 13;</code>
       */
      public Builder setUpperWarning(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        upperWarning_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string upperWarning = 13;</code>
       */
      public Builder clearUpperWarning() {
        
        upperWarning_ = getDefaultInstance().getUpperWarning();
        onChanged();
        return this;
      }
      /**
       * <code>string upperWarning = 13;</code>
       */
      public Builder setUpperWarningBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        upperWarning_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bean.Alarm)
    }

    // @@protoc_insertion_point(class_scope:bean.Alarm)
    private static final com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm();
    }

    public static com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Alarm>
        PARSER = new com.google.protobuf.AbstractParser<Alarm>() {
      public Alarm parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Alarm(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Alarm> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Alarm> getParserForType() {
      return PARSER;
    }

    public com.brix.testbed.monitor.protobuf.TestBedAlarmProto.Alarm getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bean_TestBedAlarm_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bean_TestBedAlarm_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bean_Alarm_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bean_Alarm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027TestBedAlarmProto.proto\022\004bean\"K\n\014TestB" +
      "edAlarm\022\014\n\004name\030\001 \001(\t\022\020\n\010hostName\030\002 \001(\t\022" +
      "\033\n\006alarms\030\003 \003(\0132\013.bean.Alarm\"\200\002\n\005Alarm\022\014" +
      "\n\004name\030\001 \001(\t\022\023\n\013doubleValue\030\002 \001(\001\022\020\n\010str" +
      "Value\030\003 \001(\t\022\020\n\010dataType\030\004 \001(\005\022\014\n\004unit\030\005 " +
      "\001(\t\022\022\n\nalarmValue\030\006 \001(\005\022\024\n\014alarmAckflag\030" +
      "\007 \001(\005\022\r\n\005seqNo\030\010 \001(\005\022\025\n\rdisplayFormat\030\t " +
      "\001(\t\022\022\n\nlowerAlarm\030\n \001(\t\022\024\n\014lowerWarning\030" +
      "\013 \001(\t\022\022\n\nupperAlarm\030\014 \001(\t\022\024\n\014upperWarnin" +
      "g\030\r \001(\tB6\n!com.brix.testbed.monitor.prot",
      "obufB\021TestBedAlarmProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bean_TestBedAlarm_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bean_TestBedAlarm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bean_TestBedAlarm_descriptor,
        new java.lang.String[] { "Name", "HostName", "Alarms", });
    internal_static_bean_Alarm_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bean_Alarm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bean_Alarm_descriptor,
        new java.lang.String[] { "Name", "DoubleValue", "StrValue", "DataType", "Unit", "AlarmValue", "AlarmAckflag", "SeqNo", "DisplayFormat", "LowerAlarm", "LowerWarning", "UpperAlarm", "UpperWarning", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
